Blockly.Msg.KruTime_URL="http://www.9flife.com";
Blockly.Msg.KruTime_Read="ReadValue";
Blockly.Msg.KruTime_Start="Start";
Blockly.Msg.KruTime_GateNum="Number of Gate :";
Blockly.Msg.KruTime_ReadTime="Read Times";
Blockly.Msg.KruTime_Gate="Gate :";
Blockly.Msg.KruTime_Stop="STOP";
Blockly.Msg.KruTime_Clear="Clear EEPROM";
Blockly.Msg.KruTime_Title="KruTime";